# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

import pandas as pd
from snakemake.utils import validate

configfile: "config/config.yaml"

studies = pd.read_csv(config["studies"], dtype=str, sep='\t').set_index(["study_id", "ancestry"], drop=False)

report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

rule test_R:
     output:
        touch('R.ok')
     script:
        "scripts/R/source_config.R"

include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/base_sumstats.smk"
include: "rules/prs_ptclump.smk"
include: "rules/prs_lassosum.smk"
include: "rules/prs_sbayesr.smk"
include: "rules/prs_prscs.smk"

