cluster:
  mkdir -p logs/slurm/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --container-mounts=/dhc/:/dhc/,/home/scratch/:/home/scratch/,/etc/slurm/:/etc/slurm/
    --container-workdir=${{PWD}}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/slurm/{rule}/{rule}-{wildcards}-%j.out
    {resources.misc}
default-resources:
  - partition=vcpu,hpcpu
  - mem_mb=4000
  - time="01:00:00"
  - misc=""
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 30
jobs: 30
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
