# This file should contain everything to configure the workflow on a global scale.

# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
studies: "config/studies.tsv"
target_list: "config/target_list.tsv"
prevalence: "config/pop_prevalence.tsv"

GenoPred_dir: "workflow/scripts/GenoPred"

#prs_methods: ['dbslmm','lassosum','ldpred2','megaprs','prscs','pt_clump']
prs_methods: ['pt_clump']


##################
# Software paths #
##################

# if you are running using the pipeline container and are having issues with R (missing packages, wrong path etc.)
# change the paths below to "/usr/local/bin/R" and "/usr/local/bin/Rscript" (i.e., the location of R in the container)

R: "R" 
Rscript: "Rscript"

# Note: Software paths are relative to the main working directory
#       If running sing the pipeline container the container, software at locations like "/bin/" or "/usr/" will not be found, unless these directories are explicitly mounted, which might cause other problems...

# only change the paths below if you really know what you are doing
# plink2 has to be up-to-date in order to perform polygenic scoring!
# tested with PLINK v2.00a3LM AVX2 Intel (20 Sep 2021)

# in the container, plink2 and plink1 are available at /usr/local/bin/plink2 and /usr/local/bin/plink
# the paths below can be set to those paths to use the container plink1 and plink2 

plink1_9: "bin/plink"
plink2: "bin/plink2"

gcta: "bin/gcta/gcta64"
gctb: "bin/gctb/gctb"
LDSC_dir: "workflow/scripts/ldsc"
LDPRED_dir: "workflow/scripts/ldpred"
DBSLMM_dir: "workflow/scripts/DBSLMM"
PRScs_dir: "workflow/scripts/PRScs/PRScs.py"

# qctool 2 is available in the prsipe container at "/usr/local/bin/qctool" 
qctool2: "bin/qctool"


###############
# Singularity #
###############

# if running snakemake with the --use-singularity, the main container to run in:

singularity:
  all: 'docker://rmonti/prspipe:0.0.2'

#################################
# 1000 genomes superpopulations #
#################################

1kg_superpop: ["EUR", "EAS", "AMR", "SAS", "AFR"]
1kg_pop: ["GBR", "FIN", "CHS", "PUR", "CDX", "CLM", "IBS", "PEL", "PJL", "KHV", "ACB", "GWD", "ESN", "BEB", "MSL", "STU", "ITU", "CEU", "YRI", "CHB", "JPT", "LWK", "ASW", "MXL", "TSI", "GIH"]
