# This file should contain everything to configure the workflow on a global scale.

# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
# samples: "config/samples.tsv"


##################
# Software paths #
##################

plink1_9: "bin/plink"
plink2: "bin/plink2"
gcta: "bin/gcta/gcta64"
gctb: "bin/gctb/gctb"


##################
# Resource paths #
##################

Impute2_1KG_dir: "resources/Impute2_1KG"
HapMap3_snplist_dir: "resources/HapMap3_snplist"
Geno_1KG_dir: "resources/Geno_1KG"

gwas_rep: "resources/ss/munged"

