# This contains everything to configure the workflow on a global scale.

#######################
# Configuration Files #
#######################

# table of GWAS summary statistics to analyse
# see https://github.com/intervene-EU-H2020/prspipe/blob/main/config/studies.tsv for an example
studies: "config/studies.tsv"

# table of target genetic data
# see https://github.com/intervene-EU-H2020/prspipe/blob/main/config/target_list.tsv for an example
target_list: "config/target_list.tsv"

# table of prevalences
# see https://github.com/intervene-EU-H2020/prspipe/blob/main/config/pop_prevalence.tsv for an example
prevalence: "config/pop_prevalence.tsv"

# path to the GenoPred repo
GenoPred_dir: "workflow/scripts/GenoPred"

###############
# PRS Methods #
###############

# list of methods to compare
prs_methods: ['dbslmm','lassosum','ldpred2','megaprs','prscs','pt_clump', 'sbayesr']


##################
# Software paths #
##################

# if you are running using the pipeline container and are having issues with R (missing packages, wrong path etc.)
# change the paths below to "/usr/local/bin/R" and "/usr/local/bin/Rscript" (i.e., the location of R in the container)

R: "R" 
Rscript: "Rscript"

# Note: Software paths are relative to the main working directory

# only change the paths below if you really know what you are doing

# tested with PLINK v2.00a3LM AVX2 Intel (20 Sep 2021)
# in the container, plink2 and plink1 are available at /usr/local/bin/plink2 and /usr/local/bin/plink (and are in the PATH)
# if running *without* container, change the paths below to bin/plink and bin/plink2, respectively, and use install_basics.sh to download the correct versions of plink1 and plink2
# a standard 64-bit non-AVX version of plink2 is located at /usr/local/bin/plink2_x86_64

plink1_9: "plink"
plink2: "plink2"

# qctool 2 is available in the prsipe container at "/usr/local/bin/qctool" (and is in the PATH)
# if running *without* container, change the path below to bin/qctool and use install_basics.sh to download qctool2
qctool2: "qctool"


# the paths below are only relevant if you want to run the PRS methods yourself, and can be left unchanged.

gcta: "bin/gcta/gcta64"
gctb: "bin/gctb/gctb"
LDSC_dir: "workflow/scripts/ldsc"
LDPRED_dir: "workflow/scripts/ldpred"
DBSLMM_dir: "workflow/scripts/DBSLMM"
PRScs_dir: "workflow/scripts/PRScs/PRScs.py"

###############
# Singularity #
###############

# if running snakemake with "--use-singularity", this parameter sets main container to run in:

singularity:
  all: 'docker://rmonti/prspipe:0.0.2'

#################################
# 1000 genomes superpopulations #
#################################

# can be left unchanged.

1kg_superpop: ["EUR", "EAS", "AMR", "SAS", "AFR"]
1kg_pop: ["GBR", "FIN", "CHS", "PUR", "CDX", "CLM", "IBS", "PEL", "PJL", "KHV", "ACB", "GWD", "ESN", "BEB", "MSL", "STU", "ITU", "CEU", "YRI", "CHB", "JPT", "LWK", "ASW", "MXL", "TSI", "GIH"]
