# This file should contain everything to configure the workflow on a global scale.

# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
studies: "config/studies.tsv"
target_list: "config/target_list.tsv"
prevalence: "config/pop_prevalence.tsv"

GenoPred_dir: "workflow/scripts/GenoPred"

prs_methods: ['dbslmm','lassosum','ldpred2','megaprs','prscs','pt_clump']

##################
# Software paths #
##################

# if you are running using the pipeline container and are having issues with R (missing packages, wrong path etc.)
# change the paths below to "/usr/local/bin/R" and "/usr/local/bin/RScript" (i.e., the location of R in the container)

R: "R" 
Rscript: "Rscript"

# names are identical to those used in GenoPred
# only change if you really know what you are doing
# plink2 has to be up-to-date in order to perform polygenic scoring!
# tested with PLINK v2.00a3LM AVX2 Intel (20 Sep 2021)

plink1_9: "bin/plink"
plink2: "bin/plink2"

gcta: "bin/gcta/gcta64"
gctb: "bin/gctb/gctb"
LDSC_dir: "workflow/scripts/ldsc"
LDPRED_dir: "workflow/scripts/ldpred"
DBSLMM_dir: "workflow/scripts/DBSLMM"
qctool2: "bin/qctool"
PRScs_dir: "workflow/scripts/PRScs/PRScs.py"


###############
# Singularity #
###############

singularity:
  all: 'docker://rmonti/prspipe:0.0.1'

#################################
# 1000 genomes superpopulations #
#################################

1kg_superpop: ["EUR", "EAS", "AMR", "SAS", "AFR"]
1kg_pop: ["GBR", "FIN", "CHS", "PUR", "CDX", "CLM", "IBS", "PEL", "PJL", "KHV", "ACB", "GWD", "ESN", "BEB", "MSL", "STU", "ITU", "CEU", "YRI", "CHB", "JPT", "LWK", "ASW", "MXL", "TSI", "GIH"]
