# This file should contain everything to configure the workflow on a global scale.

# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
studies: "config/studies.tsv"

GenoPred_dir: "workflow/scripts/GenoPred"
Python_scr_dir: "workflow/scripts/Python"
R_scr_dir: "workflow/scripts/R"

# 1000 genomes superpopulations:
1kg_superpop: ["EUR", "EAS", "AMR", "SAS", "AFR"]
1kg_pop: ["GBR", "FIN", "CHS", "PUR", "CDX", "CLM", "IBS", "PEL", "PJL", "KHV", "ACB", "GWD", "ESN", "BEB", "MSL", "STU", "ITU", "CEU", "YRI", "CHB", "JPT", "LWK", "ASW", "MXL", "TSI", "GIH"]


##############
# parameters #
##############

# use this many SNPs to calculate SBayesR LD-matrix in chunks
sbayesr_ldm_chunksize: 20000


##################
# Software paths #
##################

# names are identical to those used in GenoPred
plink1_9: "bin/plink"
plink2: "bin/plink2"
gcta: "bin/gcta/gcta64"
gctb: "bin/gctb/gctb"
prsice_path: "bin/"
qctool2: "bin/qctool"
PRScs_dir: "workflow/scripts/PRScs/PRScs.py"

##################
# Resource paths #
##################

Impute2_1KG_dir: "resources/Impute2_1KG"
HapMap3_snplist_dir: "resources/HapMap3_snplist"
Geno_1KG_dir: "resources/Geno_1KG"

genetic_map: "resources/genetic_map"

Base_sumstats_dir: "resources/Base_sumstats"

gwas_rep: "resources/ss/munged"

UKBB_original: "/mnt/projects/ukbiobank/original/genetics/imputed/EGAD00010001474/"
UKBB_fam: "/mnt/projects/ukbiobank/original/genetics/imputed/sample/ukb40502_imp_chr1_v3_s487296.sample"
UKBB_output: "results/UKBB"


