$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  studies:
    type: string
  target_list:
    type: string
  prevalence:
    type: string
  plink1_9:
    type: string
  plink2:
    type: string
  qctool2:
    type: string
  gcta:
    type: string
  gctb:
    type: string
  GenoPred_dir:
    type: string
  prs_methods:
    type: array

# entries that have to be in the config file for successful validation
required:
  - plink1_9
  - plink2
  - studies
  - target_list
  - prevalence
  