$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  plink1_9:
    type: string
  plink2:
    type: string
  gcta:
    type: string
  gctb:
    type: string

# entries that have to be in the config file for successful validation
required:
  - plink1_9
  - plink2
# - samples
